version: '3.8'

services:
  rabbit:
    env_file:
      - .docker/.env
    image: rabbitmq:3-management
    ports:
      - ${HTTP_RABBIT_MANAGEMENT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  nginx:
    environment:
      APP_ENV: prod
    build:
      dockerfile: .docker/nginx/Dockerfile
      context: .
    ports:
      - ${HTTP_APPLICATION_PORT}:80
    env_file:
      - .docker/.env
    depends_on:
      - php-fpm
    links:
      - php-fpm
  php-fpm:
    environment:
      APP_ENV: prod
    build:
      target: builder
      dockerfile: .docker/php/Dockerfile
      context: .
    links:
      - mariadb
      - rabbit
  mariadb:
    env_file:
      - .docker/.env
    image: helppc/mariadb:v2.0.1
    ports:
      - ${MARIADB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
