version: '3.8'

services:
  browserless:
    image: browserless/chrome
    env_file:
      - .docker/.env
    ports:
      - ${HTTP_BROWSERLESS_PORT}:3000
  minio:
    env_file:
      - .docker/.env
    image: minio/minio:RELEASE.2020-09-10T22-02-45Z
    command: server /export
    ports:
      - ${MINIO_PORT}:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./.docker/storage:/export
  devmail:
    env_file:
      - .docker/.env
    image: djfarrelly/maildev
    ports:
      - ${HTTP_DEVMAIL_PORT}:80
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    links:
      - mariadb
    ports:
      - ${ADMINER_PORT}:8080
  mariadb:
    volumes:
      - ./.docker/database:/var/lib/mysql
  nginx:
    volumes:
      #- .:/var/www
      - ./var/log/nginx:/var/log/nginx
  phpstan:
    volumes:
      - applicationData:/app
    image: phpstan/phpstan:latest
    env_file:
      - .docker/.env
    command: analyse -c phpstan.neon --ansi --pro
    ports:
      - ${PHPSTAN_PRO_WEB_PORT}:${PHPSTAN_PRO_WEB_PORT}
  php-fpm:
    environment:
      APP_ENV: dev
      COMPOSER_MEMORY_LIMIT: -1
    links:
      - devmail
    volumes:
      - ./.docker/.composerAuth.json:/root/.config/composer/auth.json
      - applicationData:/var/www

volumes:
  applicationData:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data$PWD"
